### PR TITLE
Moved the select functions out of the main class, + a couple small tweaks

### PR DESCRIPTION
**Pull request by MightyBOBcnc**
See the commit notes from the branch for details.  It looks like a huge messy change but it's mostly just removing one level of indentation + some small tweaks.  

It looks messy in the github preview because unfortunately it gets confused about halfway through and it starts to get its lines mixed up.  It might be simpler to actually open both up in a text editor for a real comparison.

### CODE REVIEW

**Comment by Stromberg90** [comment]
I've invited you as a collaborator, so you don't have to go through the pull request system :)

**Comment by MightyBOBcnc** [comment]
Thank you for the invite.  Before I start doing direct contributions I think we should set some base expectations.  Namely: 

1) I think I would like to use my fork as basically my 'dev' branch where I do ugly code experiments (you should see my dev file, it has SO many ugly inline comments :P ) and then only commit nice clean updates upstream to your repo once I've worked out the kinks in mine.

2) What are your thoughts on giant commits vs smaller/incremental commits?  I've actually been working on a very substantial series of changes to the addon in my own branch.  (These are mostly optimization/efficiency changes intended to increase the performance/speed of the addon with high-poly meshes; there are only a few user-facing changes.)  <br>
I could push it all in one or two big commits all at once, or I could do it in several smaller or small-medium commits so that there is a clear **progression** of changes that can be more easily seen by going backwards in the commit history.

3) What is your opinion on using code from other addons (if the license allows for it)?  I found an addon called Loopanar that has some nice functions for selecting bounded edge loops and edge rings between two selected edges that works nicely to replace `shortest_path_select` in `maya_edge_select` so it no longer has problems with choosing an incorrect path.  The code is released into the Public Domain.  I'd add nemyax into the Author credits.
https://www.youtube.com/watch?v=qI5j05e8Hyo
https://sourceforge.net/p/blendamajigs/wiki/Loopanar/

**Comment by Stromberg90** [comment]
All of those are fine by me, and I don't have any preference with smaller or larger commits :)

**Comment by MightyBOBcnc** [comment]
Alright.  More commits coming in the near future. :)

**Pull request merged**
