### PR TITLE
Mega merge tool 1.2.0 update

### LINKED ISSUE #23: Merge Tool : Request , preserve right click for navigation
A tiny request, can "right click"  "left click" and "alt" be preserved for navigation to work around the mesh without the need to exit and re_enter the tool, maybe as an addon preferences ?

Now i understand ,this will need a little more work than what i was thinking.

An ideal workflow will be : 

M or( something else) to enter the tool .
Esc to exit the tool.

I understand also that adding ctrl+z inside the tool will require more work, but it's not that a big deal since you can exit the tool and then ctrl+z.

### PR DESCRIPTION
**Pull request by MightyBOBcnc**
@Stromberg90 I have some goodies for you.  I made a big update to the Merge Tool that turns it into an actual tool on the Toolbar and added Edge merging support and some user configuration options.

Adding an icon for the toolbar means the add-on has more than 1 file now so it's distributed as a .zip.

Check out the update to the readme (might want a new .gif for the tool; what add-on is used to show the key presses on screen?)
https://github.com/Stromberg90/Scripts/tree/Mega-MergeTool-Update/Blender

Zip here:
https://github.com/Stromberg90/Scripts/raw/Mega-MergeTool-Update/Blender/mesh_merge_tool.zip

### CODE REVIEW

**Comment by Stromberg90** [comment]
I'm very grateful for the work you have done :)
For the gif I used Screencast Keys which comes with blender(I believe).

I'm thinking it could be nice in the future, to zip the addons and put them under the release section https://github.com/Stromberg90/Scripts/releases makes it easier to link to, find and download.
maybe with that one can incorporate downloading updates from inside blender.

**Comment by MightyBOBcnc** [comment]
Added a new .gif for the readme page.  I think the pull request is ready now.


Regarding github's Releases feature, I'll test that on my forked repo and see how well it works before committing anything to yours.  I messed around with it once in the past and it packaged the whole repo together (all the Blender, Max, and Maya folders) for the source code which was messy; maybe there was an option to manually supply the source so it wouldn't package all the add-ons together.

**Comment by Stromberg90** [comment]
New gif looks great :)
I had a quick look at this article https://medium.com/@Keithweaver_/zip-code-base-with-github-actions-for-releases-aca66f530dae
it mentions that one can use regex to exclude parts from the gif, and I'm guessing one can do that to include parts as well.

**Comment by MightyBOBcnc** [comment]
I'm not sure if that can control what goes in the source .zip and .tar.gz archives or just the release.  It's a bit above my head.

I think the bigger issue is that having multiple independent scripts all in the same repo means that making releases for each one--with each being on its own version number--makes the Tagging messy.
https://github.com/MightyBOBcnc/Scripts/tags
https://github.com/MightyBOBcnc/Scripts/releases

Admittedly this is probably my own fault for not making a test release for 0.2.4 until after the commit for 1.0.3 but, for example, 1.0.3 is the latest Edge to Curve and 0.2.4 is my latest dev experiment with Context Select but in the screenshot below those tags are applied to the full repo and both pointed at the same commit hash.  That could probably be alleviated by doing timely releases when each script is updated but the tagging situation is still a bit messy.

image

I *think* the only way to have 'clean' releases and tagging is if each script has its own individual repo.  This is a somewhat frustrating limitation with github because there isn't any convenient grouping mechanism to organize related repos (e.g. a group of Blender script repos, a group of Maya script repos, etc.) that I'm aware of.  Nothing beats the convenience of simply segregating by folders like like the way the repo is currently structured, but that results in the release/tagging issue.

**Pull request merged**
